In [1]:
from scipy.spatial.transform import Rotation as R
from pyapriltags import Detector

In [2]:
at_detector = Detector(families='tag16h5',
                        nthreads=1,
                        quad_decimate=1.0,
                        quad_sigma=0.0,
                        refine_edges=1,
                        decode_sharpening=0.25,
                        debug=0)
fx = 460.92495728   # FOV(x) -> depth2xyz -> focal length (x)
fy = 460.85058594   # FOV(y) -> depth2xyz -> focal length (y)
cx = 315.10949707   # 640 (width) 320
cy = 176.72598267   # 360 (height) 180
#cam_intrinsic_params = open3d.camera.PinholeCameraIntrinsic(640, 360, fx, fy, cx, cy)
camera_params = ( fx, fy, cx, cy )

In [ ]:
"""
import cv2
$cam = cv2.VideoCapture(0)
img = None
check, frame = cam.read()
img = frame
cv2.imshow('video', frame)
key = cv2.waitKey(1)
from PIL import Image
im = Image.fromarray(img)
im.save("april_tag.jpeg")
"""

In [4]:
import cv2
imagepath = '/Users/shanmugamr/Downloads/tag0.jpg'
frame = cv2.imread(imagepath) #, cv2.IMREAD_GRAYSCALE)

d = at_detector.detect(
  cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY), True, camera_params, 2.5)
found_tag = False
    

In [5]:
d [Detection object:
tag_family = b'tag16h5'
tag_id = 0
hamming = 0
decision_margin = 111.5625
homography = [[ 4.50083542e+02 -2.30152067e-02  5.99961263e+02]
 [ 1.07083763e-03  4.49894315e+02  5.99797480e+02]
 [ 7.29751724e-06 -1.74734580e-04  1.00000000e+00]]
center = [599.96126272 599.79747964]
corners = [[ 149.88198853 1049.88183594]
 [1050.19763184 1049.86865234]
 [1049.87670898  149.87695312]
 [ 149.87564087  149.8769989 ]]
pose_R = [[ 9.99999997e-01  7.08723636e-05  3.48583051e-05]
 [-7.08768416e-05  9.99999989e-01  1.28476923e-04]
 [-3.48491992e-05 -1.28479393e-04  9.99999991e-01]]
pose_t = [[0.79112576]
 [1.17533476]
 [1.28022171]]
pose_err = 7.368448986095677e-08
]

([Detection object:
  tag_family = b'tag16h5'
  tag_id = 0
  tag_size = 2.5
  hamming = 0
  decision_margin = 111.5625
  homography = [[ 4.50083583e+02 -2.30152088e-02  5.99961293e+02]
   [ 1.14204943e-03  4.49894315e+02  5.99797480e+02]
   [ 7.36534606e-06 -1.74734592e-04  1.00000000e+00]]
  center = [599.96129325 599.79747964]
  corners = [[ 149.88198853 1049.88183594]
   [1050.19763184 1049.86865234]
   [1049.87670898  149.87701416]
   [ 149.87564087  149.87693787]]
  pose_R = [[ 9.99999997e-01  7.08170246e-05  3.48079883e-05]
   [-7.08214959e-05  9.99999989e-01  1.28471538e-04]
   [-3.47988900e-05 -1.28474003e-04  9.99999991e-01]]
  pose_t = [[0.7911258 ]
   [1.17533475]
   [1.28022169]]
  pose_err = 7.374564733972655e-08],
 <pyapriltags.apriltags._ApriltagDetectionInfo at 0x287c390c0>)

In [71]:
apriltag.contents.family.contents.ncodes

30

In [50]:
zarray_get(detections, 0, ctypes.byref(apriltag))

In [51]:
np.ctypeslib.as_array(apriltag.contents.c)

array([599.96129325, 599.79747964])

In [52]:
apriltag.contents.decision_margin


111.5625

In [53]:
apriltag.contents.hamming

0

In [54]:
np.ctypeslib.as_array(apriltag.contents.p)

array([[ 149.88198853, 1049.88183594],
       [1050.19763184, 1049.86865234],
       [1049.87670898,  149.87701416],
       [ 149.87564087,  149.87693787]])

In [55]:
apriltag.contents.id

0

In [73]:
apriltag.contents.H.contents.nrows

3

In [74]:
apriltag.contents.H.contents.ncols

3

In [78]:
np.ctypeslib.as_array(apriltag.contents.H.contents.data)

array([450.08358301])

In [61]:
apriltag.contents.family

In [26]:
tags[0]

Detection object:
tag_family = b'tag16h5'
tag_id = 0
tag_size = 2.5
hamming = 0
decision_margin = 111.5625
homography = [[ 4.50083583e+02 -2.30152088e-02  5.99961293e+02]
 [ 1.14204943e-03  4.49894315e+02  5.99797480e+02]
 [ 7.36534606e-06 -1.74734592e-04  1.00000000e+00]]
center = [599.96129325 599.79747964]
corners = [[ 149.88198853 1049.88183594]
 [1050.19763184 1049.86865234]
 [1049.87670898  149.87701416]
 [ 149.87564087  149.87693787]]
pose_R = [[ 9.99999997e-01  7.08170246e-05  3.48079883e-05]
 [-7.08214959e-05  9.99999989e-01  1.28471538e-04]
 [-3.47988900e-05 -1.28474003e-04  9.99999991e-01]]
pose_t = [[0.7911258 ]
 [1.17533475]
 [1.28022169]]
pose_err = 7.374564733972655e-08

In [29]:
getattr(apriltag.contents,"c") 

In [27]:
for field_name, field_type in detections._fields_:
...     print(field_name, getattr(s, field_name))

AttributeError: 'LP__ZArray' object has no attribute '_fields_'

In [14]:
apriltag.contents.c

In [5]:
tags[0]

Detection object:
tag_family = b'tag16h5'
tag_id = 0
tag_size = 2.5
hamming = 0
decision_margin = 111.5625
homography = [[ 4.50083583e+02 -2.30152088e-02  5.99961293e+02]
 [ 1.14204943e-03  4.49894315e+02  5.99797480e+02]
 [ 7.36534606e-06 -1.74734592e-04  1.00000000e+00]]
center = [599.96129325 599.79747964]
corners = [[ 149.88198853 1049.88183594]
 [1050.19763184 1049.86865234]
 [1049.87670898  149.87701416]
 [ 149.87564087  149.87693787]]
pose_R = [[ 9.99999997e-01  7.08170246e-05  3.48079883e-05]
 [-7.08214959e-05  9.99999989e-01  1.28471538e-04]
 [-3.47988900e-05 -1.28474003e-04  9.99999991e-01]]
pose_t = [[0.7911258 ]
 [1.17533475]
 [1.28022169]]
pose_err = 7.374564733972655e-08

In [ ]:
tag = tags[0]
print(tag.tag_id)
print(tag.pose_R, tag.pose_t)

In [ ]:
from scipy.spatial.transform import Rotation as R
print("Rotation: ", R.from_matrix(tag.pose_R).as_rotvec(degrees=True))
print("Rotation: ", R.from_matrix(tag.pose_R).as_euler("zyx", degrees=True))

In [ ]:
z_axis_rotation = # get first element

In [ ]:
tag.pose_t #xyz

In [ ]:
import numpy as np
import cv2
from pyapriltags import Detector
from scipy.spatial.transform import Rotation
​
#######################################################################################
## Camera Config
#######################################################################################
​
T_robot_camera = np.array([
  [ 0.000, -0.342,  0.940, -14],
  [-1.000,  0.000,  0.000,   0],
  [ 0.000, -0.940, -0.342,  11],
  [ 0.000,  0.000,  0.000,   1]
], np.float32) # camera in reference frame of robot, you will need to calibrate this
T_camera_robot = np.linalg.inv(T_robot_camera)
​
fx = 460.92495728
fy = 460.85058594
cx = 315.10949707
cy = 176.72598267
camera_params = ( fx, fy, cx, cy )
​
#######################################################################################
## Tag Config
#######################################################################################
​
tag_size = 3.0 # on a 4in apriltag, only the interior black square is measured
​
tag_poses = {
  1: np.array([
    [0, 0, -1, -72],
    [1, 0, 0, 24],
    [0, -1, 0, 0],
    [0, 0, 0, 1],
  ], np.float32),
  2: np.array([
    [1, 0, 0, -24],
    [0, 0, 1, 72],
    [0, -1, 0, 0],
    [0, 0, 0, 1],
  ], np.float32),
  3: np.array([
    [1, 0, 0, 24],
    [0, 0, 1, 72],
    [0, -1, 0, 0],
    [0, 0, 0, 1],
  ], np.float32),
  4: np.array([
    [0, 0, 1, 72],
    [-1, 0, 0, 24],
    [0, -1, 0, 0],
    [0, 0, 0, 1],
  ], np.float32),
  5: np.array([
    [0, 0, 1, 72],
    [-1, 0, 0, -24],
    [0, -1, 0, 0],
    [0, 0, 0, 1],
  ], np.float32),
  6: np.array([
    [-1, 0, 0, 24],
    [0, 0, -1, -72],
    [0, -1, 0, 0],
    [0, 0, 0, 1],
  ], np.float32),
  7: np.array([
    [-1, 0, 0, -24],
    [0, 0, -1, -72],
    [0, -1, 0, 0],
    [0, 0, 0, 1],
  ], np.float32),
  8: np.array([
    [0, 0, -1, -72],
    [1, 0, 0, -24],
    [0, -1, 0, 0],
    [0, 0, 0, 1],
  ], np.float32),
}
​
​
#######################################################################################
## Apriltag Localization!!!
#######################################################################################
​
detector = Detector(
  families='tag16h5',
  nthreads=1,
  quad_decimate=1.0,
  quad_sigma=0.0,
  refine_edges=1,
  decode_sharpening=0.25,
  debug=0)
​
def detect(color_image):
  tags = detector.detect(
        img=cv2.cvtColor(color_image, cv2.COLOR_BGR2GRAY),
        estimate_tag_pose=True,
        camera_params=camera_params,
        tag_size=tag_size)
      
  tags = [tag for tag in tags if tag.decision_margin > 50 and tag.tag_id in tag_poses.keys()]
  return tags
​
def Rt2T(R, t):
  T = np.eye(4, dtype=np.float32)
  T[:3, :3] = R
  T[:3, 3:] = t
  return T
​
def localize(tags):
  # use the formula present in the video, just with the first tag
  if len(tags) == 0: return None
  tag = tags[0]
  T_camera_apriltag = Rt2T(tag.pose_R, tag.pose_t)
  T_map_apriltag = tag_poses[tag.tag_id]
  T_apriltag_camera = np.linalg.inv(T_camera_apriltag)
  T_map_robot = T_map_apriltag @ T_apriltag_camera @ T_camera_robot
  return T_map_robot
​
if __name__ == "__main__":
  # robot = RemoteInterface(...)
  # camera = RealsenseCamera()
  camera = cv2.VideoCapture(0)
​
  while True:
    # color, depth, sensors = robot.read()
    # color, depth = camera.read()
    _, color = camera.read()
    if color is not None:
      tags = detect(color)
      T = localize(tags)
      if T is not None: # we found a position!
        x, y = T[0, 3], T[1, 3]
        yaw = Rotation.from_matrix(T[:3, :3]).as_euler("zyx", degrees=True)[0]
        print(x, y, yaw)
      else:
        print("no tags found, so we can't localize")
Collapse

In [32]:
import ctypes
import os
import sys
from typing import Any, Dict, List, NamedTuple, Optional, Tuple, Union

import numpy

dir_path = '/Users/shanmugamr/python_tests/lib/python3.10/site-packages/pyapriltags'

In [33]:
class _ImageU8(ctypes.Structure):
    """Wraps image_u8 C struct."""
    _fields_ = [
        ('width', ctypes.c_int),
        ('height', ctypes.c_int),
        ('stride', ctypes.c_int),
        ('buf', ctypes.POINTER(ctypes.c_uint8))
    ]


class _Matd(ctypes.Structure):
    """Wraps matd C struct."""
    _fields_ = [
        ('nrows', ctypes.c_int),
        ('ncols', ctypes.c_int),
        ('data', ctypes.c_double * 1),
    ]


class _ZArray(ctypes.Structure):
    """Wraps zarray C struct."""
    _fields_ = [
        ('el_sz', ctypes.c_size_t),
        ('size', ctypes.c_int),
        ('alloc', ctypes.c_int),
        ('data', ctypes.c_void_p)
    ]


class _ApriltagFamily(ctypes.Structure):
    """Wraps apriltag_family C struct."""
    _fields_ = [
        ('ncodes', ctypes.c_uint32),
        ('codes', ctypes.POINTER(ctypes.c_uint64)),
        ('width_at_border', ctypes.c_int),
        ('total_width', ctypes.c_int),
        ('reversed_border', ctypes.c_bool),
        ('nbits', ctypes.c_uint32),
        ('bit_x', ctypes.POINTER(ctypes.c_int32)),
        ('bit_y', ctypes.POINTER(ctypes.c_int32)),
        ('h', ctypes.c_int32),
        ('name', ctypes.c_char_p),
    ]


class _ApriltagDetection(ctypes.Structure):
    """Wraps apriltag_detection C struct."""
    _fields_ = [
        ('family', ctypes.POINTER(_ApriltagFamily)),
        ('id', ctypes.c_int),
        ('hamming', ctypes.c_int),
        ('decision_margin', ctypes.c_float),
        ('H', ctypes.POINTER(_Matd)),
        ('c', ctypes.c_double * 2),
        ('p', (ctypes.c_double * 2) * 4)
    ]


class _ApriltagDetector(ctypes.Structure):
    """Wraps apriltag_detector C struct."""
    _fields_ = [
        ('nthreads', ctypes.c_int),
        ('quad_decimate', ctypes.c_float),
        ('quad_sigma', ctypes.c_float),
        ('refine_edges', ctypes.c_int),
        ('decode_sharpening', ctypes.c_double),
        ('debug', ctypes.c_int)
    ]


class _ApriltagDetectionInfo(ctypes.Structure):
    """Wraps apriltag_detection_info C struct."""
    _fields_ = [
        ('det', ctypes.POINTER(_ApriltagDetection)),
        ('tagsize', ctypes.c_double),
        ('fx', ctypes.c_double),
        ('fy', ctypes.c_double),
        ('cx', ctypes.c_double),
        ('cy', ctypes.c_double)
    ]


class _ApriltagPose(ctypes.Structure):
    """Wraps apriltag_pose C struct."""
    _fields_ = [
        ('R', ctypes.POINTER(_Matd)),
        ('t', ctypes.POINTER(_Matd))
    ]


In [34]:
def _ptr_to_array2d(datatype, ptr, rows, cols):
    array_type = (datatype * cols) * rows
    array_buf = array_type.from_address(ctypes.addressof(ptr))
    return numpy.ctypeslib.as_array(array_buf, shape=(rows, cols))


def _image_u8_get_array(img_ptr):
    return _ptr_to_array2d(ctypes.c_uint8,
                           img_ptr.contents.buf.contents,
                           img_ptr.contents.height,
                           img_ptr.contents.stride)


def _matd_get_array(mat_ptr):
    return _ptr_to_array2d(ctypes.c_double,
                           mat_ptr.contents.data,
                           int(mat_ptr.contents.nrows),
                           int(mat_ptr.contents.ncols))


def zarray_get(za, idx, ptr):
    # memcpy(p, &za->data[idx*za->el_sz], za->el_sz);
    #
    # p                           = ptr
    # za->el_sz                   = za.contents.el_sz
    # &za->data[idx*za->el_sz]    = za.contents.data+idx*za.contents.el_sz

    ctypes.memmove(ptr, za.contents.data + idx * za.contents.el_sz, za.contents.el_sz)


In [35]:
class Detection(NamedTuple):
    """
    Combined pythonic wrapper for apriltag_detection and apriltag_pose
    """
    tag_family: bytes
    tag_id: int
    hamming: int
    decision_margin: float
    homography: numpy.ndarray
    center: numpy.ndarray
    corners: numpy.ndarray
    pose_R: Optional[numpy.ndarray] = None
    pose_t: Optional[numpy.ndarray] = None
    pose_err: Optional[float] = None
    tag_size: Optional[float] = None

    def __str__(self):
        return ('Detection object:' +
                '\ntag_family = ' + str(self.tag_family) +
                '\ntag_id = ' + str(self.tag_id) +
                '\ntag_size = ' + str(self.tag_size) +
                '\nhamming = ' + str(self.hamming) +
                '\ndecision_margin = ' + str(self.decision_margin) +
                '\nhomography = ' + str(self.homography) +
                '\ncenter = ' + str(self.center) +
                '\ncorners = ' + str(self.corners) +
                '\npose_R = ' + str(self.pose_R) +
                '\npose_t = ' + str(self.pose_t) +
                '\npose_err = ' + str(self.pose_err) + '\n')

    def __repr__(self):
        return self.__str__()

In [41]:
class Detector(object):
    """
    Pythonic wrapper for apriltag_detector.

    families:           Tag families, separated with a space, default: tag36h11
    nthreads:           Number of threads, default: 1
    quad_decimate:      Detection of quads can be done on a lower-resolution image, improving
                        speed at a cost of pose accuracy and a slight decrease in detection
                        rate. Decoding the binary payload is still done at full resolution,
                        default: 2.0
    quad_sigma:         What Gaussian blur should be applied to the segmented image (used for
                        quad detection?)  Parameter is the standard deviation in pixels.
                        Very noisy images benefit from non-zero values (e.g. 0.8),
                        default: 0.0
    refine_edges:       When non-zero, the edges of the each quad are adjusted to "snap to"
                        strong gradients nearby. This is useful when decimation is employed,
                        as it can increase the quality of the initial quad estimate
                        substantially. Generally recommended to be on (1). Very
                        computationally inexpensive. Option is ignored if quad_decimate = 1,
                        default: 1
    decode_sharpening:  How much sharpening should be done to decoded images? This can help
                        decode small tags but may or may not help in odd lighting conditions
                        or low light conditions, default = 0.25
    searchpath:         Where to look for the Apriltag 3 library, must be a list,
                        default: ['apriltags']
    debug:              If 1, will save debug images. Runs very slow, default: 0
    """

    _SUPPORTED_FAMILIES = (
        'tag16h5',
        'tag25h9',
        'tag36h11',
        'tagCircle21h7',
        'tagCircle49h12',
        'tagCustom48h12',
        'tagStandard41h12',
        'tagStandard52h13',
    )

    def __init__(self,
                 families: str = 'tag36h11',
                 nthreads: int = 1,
                 quad_decimate: float = 2.0,
                 quad_sigma: float = 0.0,
                 refine_edges: int = 1,
                 decode_sharpening: float = 0.25,
                 debug: int = 0,
                 searchpath: List[str] = ['apriltags', '.', dir_path]):

        # Parse the parameters
        self.params: Dict[str, Any] = dict()
        self.params['families'] = families.split()
        self.params['nthreads'] = nthreads
        self.params['quad_decimate'] = quad_decimate
        self.params['quad_sigma'] = quad_sigma
        self.params['refine_edges'] = refine_edges
        self.params['decode_sharpening'] = decode_sharpening
        self.params['debug'] = debug

        # detect OS to get extension for DLL
        platform = sys.platform
        if platform.startswith('linux'):
            extension = '.so'
        elif platform.startswith('darwin'):
            extension = '.dylib'
        elif platform == 'win32':
            extension = '.dll'
        else:
            raise NotImplementedError(f"The platform {platform} is not supported")

        filename = 'libapriltag' + extension

        self.libc = None
        self.tag_detector = None
        self.tag_detector_ptr = None

        for path in searchpath:
            relpath = os.path.join('pyapriltags', path, filename)
            if os.path.exists(relpath):
                self.libc = ctypes.CDLL(relpath)
                break

        # if full path not found just try opening the raw filename;
        # this should search whatever paths dlopen is supposed to
        # search.
        if self.libc is None:
            self.libc = ctypes.CDLL(os.path.join('pyapriltags', filename))

        if self.libc is None:
            raise RuntimeError('could not find DLL named ' + filename)

        # setup the return types for all the functions used from the DLL
        self._setup_restype()

        # create the c-_apriltag_detector object
        self.tag_detector_ptr = self.libc.apriltag_detector_create()

        # create the family
        self.tag_families = dict()
        for family in self.params['families']:
            if family in self._SUPPORTED_FAMILIES:
                # Call the family's create method
                self.tag_families[family] = getattr(self.libc, f'{family}_create')()
                self.libc.apriltag_detector_add_family_bits(
                    self.tag_detector_ptr,
                    self.tag_families[family],
                    2,
                )
            else:
                raise Exception(
                    'Unrecognized tag family name. Use e.g. \'tag36h11\'.\n')

        # configure the parameters of the detector
        self.tag_detector_ptr.contents.nthreads = int(self.params['nthreads'])
        self.tag_detector_ptr.contents.quad_decimate = float(self.params['quad_decimate'])
        self.tag_detector_ptr.contents.quad_sigma = float(self.params['quad_sigma'])
        self.tag_detector_ptr.contents.refine_edges = int(self.params['refine_edges'])
        self.tag_detector_ptr.contents.decode_sharpening = int(self.params['decode_sharpening'])  # noqa: E501
        self.tag_detector_ptr.contents.debug = int(self.params['debug'])

    def _setup_restype(self):
        """Setup the return types for all the functions used from the DLL."""
        # Functions used in __init__
        self.libc.apriltag_detector_create.restype = ctypes.POINTER(_ApriltagDetector)
        self.libc.apriltag_detector_add_family_bits.restype = None
        self.libc.apriltag_detector_destroy.restype = None

        # Tag family constructors and destructors
        for family in self._SUPPORTED_FAMILIES:
            getattr(self.libc, f'{family}_create').restype = ctypes.POINTER(_ApriltagFamily)
            getattr(self.libc, f'{family}_destroy').restype = None

        # Functions used by detect()
        self.libc.apriltag_detector_detect.restype = ctypes.POINTER(_ZArray)
        self.libc.estimate_tag_pose.restype = ctypes.c_double
        self.libc.matd_destroy.restype = None
        self.libc.matd_destroy.restype = None
        self.libc.image_u8_destroy.restype = None
        self.libc.apriltag_detections_destroy.restype = None
        self.libc.image_u8_create.restype = ctypes.POINTER(_ImageU8)

    def __del__(self):
        if self.tag_detector_ptr is not None:
            # destroy the detector
            self.libc.apriltag_detector_destroy(self.tag_detector_ptr)

            # destroy the tag families
            for family, tf in self.tag_families.items():
                if family in self._SUPPORTED_FAMILIES:
                    # Call the family's destroy method
                    getattr(self.libc, f'{family}_destroy')(tf)

    def detect(
        self, img: numpy.ndarray, estimate_tag_pose: bool = False,
        camera_params: Union[numpy.ndarray, Tuple[float, float, float, float], None] = None,
        tag_size: Union[float, None, Dict[int, float]] = None,
    ):
        """
        Run detectons on the provided image. The image must be a grayscale
        image of type numpy.uint8.
        """
        assert len(img.shape) == 2
        assert img.dtype == numpy.uint8

        c_img = self._convert_image(img)

        return_info = []

        if self.libc is None:
            raise RuntimeError('No DLL found')

        # detect apriltags in the image
        detections = self.libc.apriltag_detector_detect(self.tag_detector_ptr, c_img)
        apriltag = ctypes.POINTER(_ApriltagDetection)()
        return detections, apriltag

    def _convert_image(self, img):
        height = img.shape[0]
        width = img.shape[1]

        c_img = self.libc.image_u8_create(width, height)

        tmp = _image_u8_get_array(c_img)

        # copy the opencv image into the destination array, accounting for the
        # difference between stride & width.
        tmp[:, :width] = img

        # tmp goes out of scope here but we don't care because
        # the underlying data is still in c_img.
        return c_img
